spring:
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password: 123123123
  application:
    name:UserCenter
  profiles:
    active: dev
  datasource:
      username: voxusers
      url: jdbc:mysql://47.113.204.154:3306/voxusers
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  #session失效时间
  session:
    timeout: 86400
  banner:
    location: banner3.txt

mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        domain: voxcode.cn
#        same-site: none
#        secure: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.vox.usercenter.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


